//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ICDWrapper {

public class ICDWrapper {
  public static void register_HelloWorld_type_identifier(SWIGTYPE_p_eprosima__fastdds__dds__xtypes__TypeIdentifierPair type_ids) {
    ICDWrapperPINVOKE.register_HelloWorld_type_identifier(SWIGTYPE_p_eprosima__fastdds__dds__xtypes__TypeIdentifierPair.getCPtr(type_ids));
    if (ICDWrapperPINVOKE.SWIGPendingException.Pending) throw ICDWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public static uint ICD_pkg_HelloWorld_max_cdr_typesize {
    get {
      uint ret = ICDWrapperPINVOKE.ICD_pkg_HelloWorld_max_cdr_typesize_get();
      return ret;
    } 
  }

  public static uint ICD_pkg_HelloWorld_max_key_cdr_typesize {
    get {
      uint ret = ICDWrapperPINVOKE.ICD_pkg_HelloWorld_max_key_cdr_typesize_get();
      return ret;
    } 
  }

  public static void serialize_key(SWIGTYPE_p_eprosima__fastcdr__Cdr scdr, HelloWorld data) {
    ICDWrapperPINVOKE.serialize_key(SWIGTYPE_p_eprosima__fastcdr__Cdr.getCPtr(scdr), HelloWorld.getCPtr(data));
    if (ICDWrapperPINVOKE.SWIGPendingException.Pending) throw ICDWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public static int dds_init(string topic_name) {
    int ret = ICDWrapperPINVOKE.dds_init(topic_name);
    return ret;
  }

  public static int dds_write(uint index, string message) {
    int ret = ICDWrapperPINVOKE.dds_write(index, message);
    return ret;
  }

  public static int dds_take(SWIGTYPE_p_unsigned_int index_out, string message_buffer, int buffer_len) {
    int ret = ICDWrapperPINVOKE.dds_take(SWIGTYPE_p_unsigned_int.getCPtr(index_out), message_buffer, buffer_len);
    return ret;
  }

  public static string dds_take_message(SWIGTYPE_p_unsigned_int index_out) {
    string ret = ICDWrapperPINVOKE.dds_take_message(SWIGTYPE_p_unsigned_int.getCPtr(index_out));
    return ret;
  }

  public static void dds_shutdown() {
    ICDWrapperPINVOKE.dds_shutdown();
  }

  public static string dds_take_string(SWIGTYPE_p_unsigned_int index_out) {
    string ret = ICDWrapperPINVOKE.dds_take_string(SWIGTYPE_p_unsigned_int.getCPtr(index_out));
    return ret;
  }

}

}
