from distutils.core import setup, Extension
import os
import sys

# Define paths
dds_message_dir = os.path.join('..', '..', 'DDSmessage')
dds_build_dir = os.path.join(dds_message_dir, 'build', 'Release')

# FastDDS installation path (adjust this to your FastDDS installation)
fastdds_root = r'C:\fastdds 3.2.2'
fastdds_include = os.path.join(fastdds_root, 'include')
fastdds_lib = os.path.join(fastdds_root, 'lib', 'x64Win64VS2019')

# Include directories
include_dirs = [
    dds_message_dir,
    fastdds_include,
    os.path.join(fastdds_include, 'fastcdr'),
    os.path.join(fastdds_include, 'fastdds'),
    os.path.join(fastdds_include, 'fastrtps'),
    os.path.join(fastdds_include, 'foonathan_memory'),
]

# Library directories  
library_dirs = [
    dds_build_dir,
    fastdds_lib
]

# Libraries to link
libraries = [
    'ICD',  # Our compiled ICD library
    'fastdds-3.2',
    'fastcdr-2.3'
]

# Define the extension module
icd_module = Extension(
    '_ICDWrapper',
    sources=[
        'ICD_wrap.cxx',  # This will be generated by SWIG
    ],
    include_dirs=include_dirs,
    library_dirs=library_dirs,
    libraries=libraries,
    define_macros=[
        ('WIN32_LEAN_AND_MEAN', None),
        ('_WIN32_WINNT', '0x0601'),
    ],
    extra_compile_args=['/std:c++17'] if sys.platform == 'win32' else ['-std=c++17'],
    language='c++'
)

setup(
    name='ICDWrapper',
    version='1.0',
    author='DDS Example',
    description='Python wrapper for DDS facade using SWIG',
    ext_modules=[icd_module],
    py_modules=['ICDWrapper'],
)
